### ISSUE TITLE
Wrong index calculation

### ISSUE THREAD

**Issue by bencz** [pocketken/H3.net#110]
I did some tests, comparing the geohash calculated by the official Uber lib vs H3.Net, and the results are completely different

For example:
This lat/long: [-23.553301290491326, -46.65526874921591]  on resolution 9

Expected result: 89a8100c187ffff
Result from H3.Net: 890326a6c73ffff

**Comment by bencz** [comment]
Ok...
I found the problem... I need to convert the lat/long to radian, to get the right response:

var resolution = 9
var latitude = -23.553301290491326;
var longitude = -46.65526874921591;

var latRad = latitude * Math.PI / 180;
var lonRad = longitude * Math.PI / 180;

var index = H3Index.FromLatLng(new LatLng(latRad, lonRad), resolution);

**Comment by pocketken** [comment]
Hmm not sure I did not get notification you had opened an issue, my apologies for not replying earlier @bencz, but glad to see you got sorted out.

`LatLng` which is modeled after the upstream library does use radians as you discovered.  If you use NTS `Point`, you can use degrees directly (note lon/lat not lat/lon as well here):

```cs
var index = H3Index.FromPoint(new Point(longitude, latitude), resolution);
```
