### ISSUE TITLE
H3 to GeoJson or Polygons

### ISSUE THREAD

**Issue by jrgcubano** [pocketken/H3.net#28]
Hello @pocketken,

First, say thank you very much for the effort to make this port to C#. We are starting a project and we would like to test H3.

Do you have any plans to implement a conversion from h3 to polygons (something similar to https://github.com/uber/geojson2h3 or close).

Thanks!

**Comment by pocketken** [comment]
Hi @jrgcubano,

No problem, glad to see someone other than myself actually using it for something :)

I haven't really thought about building any specific tools as part of this project, but, the basic API elements for being able to achieve conversion to/from `Geometry` and `H3Index` are there:

 * the `Fill` and `GetIndicies` (which I have just realized is spelled wrong) extension methods in `H3.Algorithms.Polyfill` can handle producing a set of `H3Index`es for a given `Polygon`, `LineString` and set of `Coordinate`s.
 * the conversion from `H3Index` to a NTS `Geometry` is provided in `H3.Extensions.H3GeometryExtensions`:
   *  the `GetCellBoundary`  method will give you the `POLYGON` boundary for a given index
   * the `GetCellBoundaries` method will produce a `MULTIPOLYGON` containing all of the boundaries for the indexes in a set.
 * you can get the `POINT` for a given index by calling `.ToPoint()`

As far as actually producing GeoJSON for the NTS geometries produced goes, they provide a number of I/O packages e.g. [GeoJsonConverterFactory](https://github.com/NetTopologySuite/NetTopologySuite.IO.GeoJSON/wiki/Using-NTS.IO.GeoJSON4STJ-with-ASP.NET-Core-MVC).

Does that address what you are looking for, or is there something specific you're trying to do that I can provide further guidance on?

**Comment by pocketken** [comment]
Oh I should also note, in lieu of some documentation if you look through the various [tests](https://github.com/pocketken/H3.net/tree/main/test/H3.Test) there's a few examples using the various API elements.  Some tests are definitely clearer than others.. one of the many things to clean up when I get some "spare time"!

**Comment by jrgcubano** [comment]
@pocketken Thanks a lot for the tips.

**Comment by jrgcubano** [comment]
@pocketken Hello there again,

We have been playing around with different use cases and until now everything works perfectly!

But another question arises... Is there any way currently to get the h3Indices related to a polygon or any plan to implement that. eg: https://github.com/uber/geojson2h3 => featureToh3.

Thanks in advance for your help.
